# Generated by Django 3.2.3 on 2021-06-29 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=100)),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicial', models.DateTimeField()),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=100)),
                ('pago', models.BooleanField(default=False)),
                ('data_final', models.DateTimeField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealing_fiado.cliente')),
                ('produtos', models.ManyToManyField(blank=True, to='dealing_fiado.Produto')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='compras_fiados',
            field=models.ManyToManyField(blank=True, related_name='cliente_compras_fiados', to='dealing_fiado.Venda'),
        ),
    ]
