# Generated by Django 3.2.3 on 2021-06-30 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealing_fiado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='data_final',
            field=models.DateTimeField(blank=True),
        ),
        migrations.RemoveField(
            model_name='venda',
            name='produtos',
        ),
        migrations.AddField(
            model_name='venda',
            name='produtos',
            field=models.TextField(blank=True),
        ),
    ]
